version: 2
jobs:
  test:
    working_directory: ~/octanner/prism-ui
    environment:
      BABEL_DISABLE_CACHE: '1'
      NODE_ENV: test
    docker:
      - image: circleci/node:10.11.0-stretch

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      # Install deps and cache
      - run: npm config set registry "http://registry.npmjs.org"
      - run: npm cache clean --force

      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Test
      - run: npm test -- --verbose --silent

  security-audit:
    docker:
      - image: circleci/node:10.11.0-stretch
    steps:
      - checkout
      - run: npm audit

workflows:
  version: 2
  run-tests-and-audit-packages:
    jobs:
      - test
      - security-audit
