version: 2
jobs:
  test:
    working_directory: ~/octanner/prism-ui
    environment:
      BABEL_DISABLE_CACHE: '1'
      NODE_ENV: test
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      # Install deps and cache
      - run: sudo npm i -g yarn@1.19.1
      - run: yarn config set registry "http://registry.npmjs.org"
      - run: yarn cache clean --force

      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Test
      - run: yarn test -- --verbose --silent

  security-audit:
    docker:
      - image: circleci/node:10.11.0-stretch
    steps:
      - checkout
      - run: sudo npm i -g yarn@1.19.1
      - run: /bin/bash -c 'yarn audit; [[$? -ge 2 ]] && exit 1 || exit 0'

workflows:
  version: 2
  run-tests-and-audit-packages:
    jobs:
      - test
      - security-audit
